# Generated by Django 3.1.5 on 2021-01-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("icon", models.CharField(max_length=255, verbose_name="icon")),
                ("description", models.TextField(verbose_name="description")),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
    ]
