# Generated by Django 3.1.5 on 2021-01-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                help_text="https://fontawesome.com/v4.7.0/icons/",
                max_length=255,
                verbose_name="icon",
            ),
        ),
    ]
