# Generated by Django 3.1.5 on 2021-01-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0004_auto_20210112_0743"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesection",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
