# Generated by Django 3.1.5 on 2021-01-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0005_sitesection_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesection',
            old_name='name',
            new_name='key',
        ),
    ]
