# Generated by Django 3.1.5 on 2021-01-17 16:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0009_auto_20210117_0914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="sitesection",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
    ]
