# Generated by Django 3.1.5 on 2021-04-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0011_auto_20210117_1741"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesection",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
