# Generated by Django 3.1.5 on 2021-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0012_sitesection_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesection",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="site_sections/"),
        ),
    ]
