# Generated by Django 3.1.5 on 2021-05-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0014_sitesection_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesection',
            name='layout',
            field=models.CharField(choices=[('introduction', 'introduction'), ('contact', 'contact'), ('team', 'team'), ('list_left', 'list_left'), ('list_right', 'list_right'), ('simple_list', 'simple_list')], default='list_left', max_length=50, verbose_name='layout'),
        ),
    ]
