# Generated by Django 3.1.5 on 2021-05-02 16:19

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0015_auto_20210502_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesection",
            name="gradient_middle",
            field=colorfield.fields.ColorField(default="#FFFFFFFF", max_length=18),
        ),
        migrations.AddField(
            model_name="sitesection",
            name="gradient_start",
            field=colorfield.fields.ColorField(default="#FFFFFFFF", max_length=18),
        ),
        migrations.AddField(
            model_name="sitesection",
            name="gradient_stop",
            field=colorfield.fields.ColorField(default="#FFFFFFFF", max_length=18),
        ),
    ]
