# Generated by Django 3.1.5 on 2021-05-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0016_auto_20210502_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesection',
            old_name='gradient_start',
            new_name='background',
        ),
    ]
