# Generated by Django 3.1.5 on 2021-05-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0017_auto_20210502_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesection',
            name='gradient_middle',
        ),
        migrations.RemoveField(
            model_name='sitesection',
            name='gradient_stop',
        ),
    ]
