# Generated by Django 6.0.1 on 2026-01-19 17:47

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0018_auto_20210502_1628"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesection",
            options={
                "ordering": ("order",),
                "verbose_name": "site_section",
                "verbose_name_plural": "site_sections",
            },
        ),
        migrations.AlterField(
            model_name="sitesection",
            name="background",
            field=colorfield.fields.ColorField(
                default="#FFFFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.CreateModel(
            name="ContentPlanning",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("maternelle", "Les maternelles"),
                            ("primaire", "Les primaires"),
                        ],
                        max_length=20,
                        verbose_name="section",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "description",
                    models.TextField(
                        help_text="Activity description (max 500 characters)",
                        max_length=500,
                        verbose_name="description",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_entries",
                        to="site_content.content",
                        verbose_name="content",
                    ),
                ),
                (
                    "educator",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True, "visible_on_site": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="educator",
                    ),
                ),
            ],
            options={
                "verbose_name": "content planning",
                "verbose_name_plural": "content planning",
                "ordering": ["date", "section"],
                "indexes": [
                    models.Index(
                        fields=["content", "date"],
                        name="site_conten_content_8b673e_idx",
                    ),
                    models.Index(
                        fields=["date", "section"], name="site_conten_date_529a42_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content", "date", "section", "educator"),
                        name="unique_planning_entry",
                    )
                ],
            },
        ),
    ]
