# Generated by Django 6.0.1 on 2026-01-19 18:00

from django.db import migrations
from bs4 import BeautifulSoup
from datetime import datetime


def migrate_wednesday_planning(apps, schema_editor):
    """Parse HTML table from Wednesday planning and create ContentPlanning entries."""
    Content = apps.get_model("site_content", "Content")
    ContentPlanning = apps.get_model("site_content", "ContentPlanning")
    User = apps.get_model("members", "User")

    # Map HTML section names to choice values
    SECTION_MAP = {
        "Les maternelles": "maternelle",
        "maternelles": "maternelle",
        "Les primaires": "primaire",
        "primaires": "primaire",
    }

    # Find Wednesday planning content (ID 6)
    try:
        content = Content.objects.get(id=6)
    except Content.DoesNotExist:
        print("⚠ Wednesday planning content (ID 6) not found, skipping migration")
        return

    if not content.show_more_content:
        print("⚠ No show_more_content found in Wednesday planning, skipping migration")
        return

    # Parse HTML table
    soup = BeautifulSoup(content.show_more_content, "html.parser")
    table = soup.find("table")

    if not table:
        print("⚠ No table found in Wednesday planning HTML, skipping migration")
        return

    rows = table.find_all("tr")
    created_count = 0
    skipped_count = 0
    errors = []
    last_date = None  # Track last valid date for rows with empty date cells

    # Process all rows (no header in this table)
    for row in rows:
        cols = row.find_all("td")
        if len(cols) != 4:
            continue

        date_str = cols[0].get_text(strip=True)
        educator_name = cols[1].get_text(strip=True)
        section_name = cols[2].get_text(strip=True)
        description = cols[3].get_text(strip=True)

        # Parse date (format: dd/mm/yyyy) or reuse last date if empty
        if date_str and date_str != "\xa0":  # \xa0 is &nbsp;
            try:
                last_date = datetime.strptime(date_str, "%d/%m/%Y").date()
                date = last_date
            except ValueError:
                errors.append(f"Invalid date format: {date_str}")
                skipped_count += 1
                continue
        elif last_date:
            # Empty date cell - reuse last valid date (multiple activities same day)
            date = last_date
        else:
            # No valid date yet
            skipped_count += 1
            continue

        # Find educator by first name (case-insensitive)
        educator = User.objects.filter(
            first_name__iexact=educator_name, is_staff=True, visible_on_site=True
        ).first()

        if not educator:
            # Try matching by last name or full name
            educator = User.objects.filter(
                last_name__iexact=educator_name, is_staff=True, visible_on_site=True
            ).first()

        if not educator:
            errors.append(f"Educator not found: {educator_name}")
            skipped_count += 1
            continue

        # Map section name to choice value
        section_choice = SECTION_MAP.get(section_name)

        if not section_choice:
            errors.append(f"Section not mapped: {section_name}")
            skipped_count += 1
            continue

        # Create ContentPlanning entry
        try:
            ContentPlanning.objects.get_or_create(
                content=content,
                date=date,
                section=section_choice,
                educator=educator,
                defaults={"description": description},
            )
            created_count += 1
        except Exception as e:
            errors.append(f"Error creating entry for {date_str}: {str(e)}")
            skipped_count += 1

    # Print summary
    print(f"✓ Created {created_count} ContentPlanning entries")
    if skipped_count > 0:
        print(f"⚠ Skipped {skipped_count} entries")
    if errors:
        print("Errors encountered:")
        for error in errors[:10]:  # Show first 10 errors
            print(f"  - {error}")
        if len(errors) > 10:
            print(f"  ... and {len(errors) - 10} more errors")


def reverse_migration(apps, schema_editor):
    """Delete all ContentPlanning entries for Wednesday planning."""
    Content = apps.get_model("site_content", "Content")
    ContentPlanning = apps.get_model("site_content", "ContentPlanning")

    try:
        content = Content.objects.get(id=6)
        deleted_count = ContentPlanning.objects.filter(content=content).count()
        ContentPlanning.objects.filter(content=content).delete()
        print(f"✓ Deleted {deleted_count} ContentPlanning entries")
    except Content.DoesNotExist:
        print("⚠ Wednesday planning content (ID 6) not found")


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0019_add_content_planning_with_choices"),
        ("members", "0014_alter_child_status"),
    ]

    operations = [
        migrations.RunPython(migrate_wednesday_planning, reverse_migration),
    ]
