# Generated by Django 6.0.1 on 2026-01-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0020_migrate_wednesday_planning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentplanning",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Activity description (max 500 characters)",
                max_length=500,
                null=True,
                verbose_name="description",
            ),
        ),
    ]
