# Generated by Django 6.0.1 on 2026-01-19 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("site_content", "0021_alter_contentplanning_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentplanning",
            name="educator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True, "visible_on_site": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="educator",
            ),
        ),
        migrations.AlterField(
            model_name="contentplanning",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("maternelle", "Les maternelles"),
                    ("primaire", "Les primaires"),
                ],
                max_length=20,
                null=True,
                verbose_name="section",
            ),
        ),
    ]
