# Generated by Django 6.0.1 on 2026-01-19 19:30

from django.db import migrations
from bs4 import BeautifulSoup
from datetime import datetime
import json
import os


def add_maxime_planning_entries(apps, schema_editor):
    """Add ContentPlanning entries for Maxime after user is created."""
    Content = apps.get_model("site_content", "Content")
    ContentPlanning = apps.get_model("site_content", "ContentPlanning")
    User = apps.get_model("members", "User")

    # Get Maxime user
    try:
        maxime = User.objects.get(email="maxime@villagedebenjamins.be")
    except User.DoesNotExist:
        print("⚠ Maxime user not found, skipping migration")
        return

    # Load section mapping
    SECTION_MAP = {
        "Les maternelles": "maternelle",
        "maternelles": "maternelle",
        "Les primaires": "primaire",
        "primaires": "primaire",
    }

    # Find Wednesday planning content (ID 6)
    try:
        content = Content.objects.get(id=6)
    except Content.DoesNotExist:
        print("⚠ Wednesday planning content (ID 6) not found, skipping migration")
        return

    if not content.show_more_content:
        print("⚠ No show_more_content found in Wednesday planning, skipping migration")
        return

    # Parse HTML table
    soup = BeautifulSoup(content.show_more_content, "html.parser")
    table = soup.find("table")

    if not table:
        print("⚠ No table found in Wednesday planning HTML, skipping migration")
        return

    rows = table.find_all("tr")
    created_count = 0
    last_date = None

    for row in rows:
        cols = row.find_all("td")
        if len(cols) < 2:
            continue

        date_str = cols[0].get_text(strip=True)
        educator_name = cols[1].get_text(strip=True) if len(cols) > 1 else ""
        section_name = cols[2].get_text(strip=True) if len(cols) > 2 else ""
        description = cols[3].get_text(strip=True) if len(cols) > 3 else ""

        # Only process Maxime entries
        if educator_name != "Maxime":
            # Update last_date if this is a date row
            if date_str and date_str != "\xa0":
                try:
                    last_date = datetime.strptime(date_str, "%d/%m/%Y").date()
                except ValueError:
                    pass
            continue

        # Parse date or reuse last date
        if date_str and date_str != "\xa0":
            try:
                last_date = datetime.strptime(date_str, "%d/%m/%Y").date()
                date = last_date
            except ValueError:
                continue
        elif last_date:
            date = last_date
        else:
            continue

        # Map section name to choice value
        section_choice = SECTION_MAP.get(section_name)
        if not section_choice:
            continue

        # Create or update ContentPlanning entry for Maxime
        try:
            ContentPlanning.objects.get_or_create(
                content=content,
                date=date,
                section=section_choice,
                educator=maxime,
                defaults={"description": description},
            )
            created_count += 1
        except Exception as e:
            print(f"⚠ Error creating entry for Maxime on {date}: {str(e)}")

    print(f"✓ Created {created_count} ContentPlanning entries for Maxime")


def reverse_migration(apps, schema_editor):
    """Remove Maxime's ContentPlanning entries."""
    ContentPlanning = apps.get_model("site_content", "ContentPlanning")
    User = apps.get_model("members", "User")

    try:
        maxime = User.objects.get(email="maxime@villagedebenjamins.be")
        deleted_count = ContentPlanning.objects.filter(educator=maxime).count()
        ContentPlanning.objects.filter(educator=maxime).delete()
        print(f"✓ Deleted {deleted_count} ContentPlanning entries for Maxime")
    except User.DoesNotExist:
        print("⚠ Maxime user not found")


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0022_alter_contentplanning_educator_section"),
        ("members", "0015_add_maxime_staff"),
    ]

    operations = [
        migrations.RunPython(add_maxime_planning_entries, reverse_migration),
    ]
