# Generated by Django 6.0.1 on 2026-01-19 20:00

from django.db import migrations
import json
import os


def populate_from_json_seed(apps, schema_editor):
    """Populate ContentPlanning from JSON seed data."""
    Content = apps.get_model("site_content", "Content")
    ContentPlanning = apps.get_model("site_content", "ContentPlanning")
    User = apps.get_model("members", "User")

    # Load JSON files
    migrations_dir = os.path.dirname(__file__)

    # Load data
    data_file = os.path.join(migrations_dir, "wednesday_data.json")
    try:
        with open(data_file, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"⚠ Data file not found: {data_file}, skipping migration")
        return
    except json.JSONDecodeError as e:
        print(f"⚠ Invalid JSON in data file: {str(e)}, skipping migration")
        return

    # Load educator mapping
    mapping_file = os.path.join(migrations_dir, "wednesday_mapping.json")
    try:
        with open(mapping_file, "r", encoding="utf-8") as f:
            educator_mapping = json.load(f)
    except FileNotFoundError:
        print(f"⚠ Mapping file not found: {mapping_file}, skipping migration")
        return
    except json.JSONDecodeError as e:
        print(f"⚠ Invalid JSON in mapping file: {str(e)}, skipping migration")
        return

    # Section mapping
    SECTION_MAP = {
        "Les maternelles": "maternelle",
        "maternelles": "maternelle",
        "Les primaires": "primaire",
        "primaires": "primaire",
    }

    # Find Wednesday planning content (ID 6)
    try:
        content = Content.objects.get(id=6)
    except Content.DoesNotExist:
        print("⚠ Wednesday planning content (ID 6) not found, skipping migration")
        return

    created_count = 0
    skipped_count = 0
    errors = []

    # Process each day's planning
    for day_plan in data.get("planning", []):
        date = day_plan.get("date")
        if not date:
            skipped_count += 1
            continue

        # Process each activity
        for activity in day_plan.get("activities", []):
            animator = activity.get("animateur", "").strip()
            group = activity.get("groupe", "").strip()
            description = activity.get("activite", "").strip()

            # Skip entries without animator or group
            if not animator or not group:
                skipped_count += 1
                continue

            # Skip entries with empty descriptions
            if not description:
                skipped_count += 1
                continue

            # Get educator from mapping
            educator = None
            educator_id = educator_mapping.get(animator)

            if educator_id:
                try:
                    educator = User.objects.get(id=educator_id)
                except User.DoesNotExist:
                    errors.append(f"User ID {educator_id} not found for {animator}")
                    skipped_count += 1
                    continue
            elif educator_id is False:
                # Special case: Maxime - lookup by email
                if animator == "Maxime":
                    try:
                        educator = User.objects.get(
                            email="maxime@villagedebenjamins.be"
                        )
                    except User.DoesNotExist:
                        errors.append(f"Maxime user not found")
                        skipped_count += 1
                        continue
                else:
                    errors.append(f"Educator marked as not existing: {animator}")
                    skipped_count += 1
                    continue
            else:
                errors.append(f"Educator not in mapping: {animator}")
                skipped_count += 1
                continue

            # Map section
            section_choice = SECTION_MAP.get(group)
            if not section_choice:
                errors.append(f"Section not mapped: {group}")
                skipped_count += 1
                continue

            # Create ContentPlanning entry
            try:
                obj, created = ContentPlanning.objects.get_or_create(
                    content=content,
                    date=date,
                    section=section_choice,
                    educator=educator,
                    defaults={"description": description},
                )
                if created:
                    created_count += 1
            except Exception as e:
                errors.append(f"Error creating entry for {date} - {animator}: {str(e)}")
                skipped_count += 1

    # Print summary
    print(f"✓ Created {created_count} new ContentPlanning entries from JSON seed")
    if skipped_count > 0:
        print(f"⚠ Skipped {skipped_count} entries")
    if errors:
        print("Errors encountered:")
        for error in errors[:10]:
            print(f"  - {error}")
        if len(errors) > 10:
            print(f"  ... and {len(errors) - 10} more errors")


def reverse_migration(apps, schema_editor):
    """Remove all ContentPlanning entries."""
    Content = apps.get_model("site_content", "Content")
    ContentPlanning = apps.get_model("site_content", "ContentPlanning")

    try:
        content = Content.objects.get(id=6)
        deleted_count = ContentPlanning.objects.filter(content=content).count()
        ContentPlanning.objects.filter(content=content).delete()
        print(f"✓ Deleted {deleted_count} ContentPlanning entries")
    except Content.DoesNotExist:
        print("⚠ Wednesday planning content (ID 6) not found")


class Migration(migrations.Migration):

    dependencies = [
        ("site_content", "0023_add_maxime_planning_entries"),
    ]

    operations = [
        migrations.RunPython(populate_from_json_seed, reverse_migration),
    ]
