# Generated by Django 6.0.1 on 2026-01-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("section", "0002_section_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ("order",),
                "verbose_name": "section",
                "verbose_name_plural": "sections",
            },
        ),
    ]
