export const UPDATE_TOKEN = 'UPDATE_TOKEN'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const INSPECT_TOKEN = 'INSPECT_TOKEN'
export const LOGOUT = 'LOGOUT'

export const GET_USER = 'GET_USER'
export const GET_CHILDREN = 'GET_CHILDREN'
export const CREATE_CHILD = 'CREATE_CHILD'
export const UPDATE_CHILD = 'UPDATE_CHILD'
export const DELETE_CHILD = 'DELETE_CHILD'

export const GET_HOLIDAYS = 'GET_HOLIDAYS'
export const CREATE_REGISTRATION = 'CREATE_REGISTRATION'
export const GET_REGISTRATIONS = 'GET_REGISTRATIONS'