# Generated by Django 3.1.3 on 2020-11-18 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('min_age', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='minimum age')),
                ('max_age', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='maximum age')),
                ('educators', models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='section', to=settings.AUTH_USER_MODEL, verbose_name='educator')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
    ]
