# Generated by Django 3.1.3 on 2020-11-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0004_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='registration_open',
            field=models.BooleanField(default=False, verbose_name='registration open'),
        ),
    ]
