# Generated by Django 3.1.3 on 2020-11-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0007_auto_20201120_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationDate',
        ),
    ]
