# Generated by Django 3.1.3 on 2020-11-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0013_auto_20201120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[['pending', 'impayée'], ['paid', 'payée'], ['cancelled', 'annulée']], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('departure_time', models.TimeField(verbose_name='departure_time')),
                ('arrival_time', models.TimeField(verbose_name='arrival_time')),
                ('transport', models.CharField(max_length=255, verbose_name='transport')),
                ('section_holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outings', to='holiday.holidaysection', verbose_name='section_holiday')),
            ],
            options={
                'verbose_name': 'outings',
            },
        ),
    ]
