# Generated by Django 3.1.3 on 2020-11-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
    ]
