# Generated by Django 3.1.3 on 2020-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_auto_20201118_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
