# Generated by Django 3.1.3 on 2020-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to="members/"),
        ),
    ]
