# Generated by Django 3.1.3 on 2020-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_auto_20201119_1556"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
