# Generated by Django 3.1.5 on 2021-05-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_auto_20210518_1936"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accept_newsletter",
            field=models.BooleanField(default=False, verbose_name="visible_on_site"),
        ),
    ]
