# Generated by Django 6.0.1 on 2026-01-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0013_auto_20210527_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_validation", "in_validation"),
                    ("registered", "registered"),
                    ("archived", "archived"),
                ],
                default="in_validation",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
