# Generated by Django 6.0.1 on 2026-01-19 19:00

from django.db import migrations


def create_maxime_staff(apps, schema_editor):
    """Create Maxime as a staff member visible on site."""
    User = apps.get_model("members", "User")

    # Check if Maxime already exists
    if User.objects.filter(email="maxime@villagedebenjamins.be").exists():
        print("✓ Maxime already exists, skipping creation")
        return

    try:
        maxime = User.objects.create(
            email="maxime@villagedebenjamins.be",
            first_name="Maxime",
            last_name="",
            is_staff=True,
            is_active=True,
            visible_on_site=True,
        )
        print(f"✓ Created staff member: Maxime (ID: {maxime.id})")
    except Exception as e:
        print(f"⚠ Error creating Maxime: {str(e)}")


def reverse_migration(apps, schema_editor):
    """Remove Maxime staff member."""
    User = apps.get_model("members", "User")

    try:
        deleted_count, _ = User.objects.filter(
            email="maxime@villagedebenjamins.be"
        ).delete()
        if deleted_count > 0:
            print(f"✓ Deleted Maxime staff member")
        else:
            print("⚠ Maxime staff member not found")
    except Exception as e:
        print(f"⚠ Error deleting Maxime: {str(e)}")


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_alter_child_status"),
    ]

    operations = [
        migrations.RunPython(create_maxime_staff, reverse_migration),
    ]
