# Generated by Django 3.1.3 on 2020-11-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_auto_20201118_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HolidayRegistrationDate',
            new_name='RegistrationDate',
        ),
    ]
