# Generated by Django 3.1.3 on 2020-11-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday", "0005_holiday_registration_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
