# Generated by Django 3.1.3 on 2020-11-20 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_auto_20201119_1606"),
        ("holiday", "0006_holiday_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="members.child",
                verbose_name="child",
            ),
        ),
    ]
