# Generated by Django 3.1.3 on 2020-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0012_auto_20201120_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[['pending', 'en attente de payment'], ['paid', 'payée'], ['cancelled', 'annulée']], default='pending', max_length=10, verbose_name='status'),
        ),
    ]
