# Generated by Django 3.1.3 on 2020-11-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("section", "0001_initial"),
        ("holiday", "0014_auto_20201122_0834"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outing",
            options={"verbose_name": "outing", "verbose_name_plural": "outings"},
        ),
        migrations.AddField(
            model_name="registration",
            name="section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="section.section",
                verbose_name="section",
            ),
            preserve_default=False,
        ),
    ]
