# Generated by Django 3.1.5 on 2021-01-17 16:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0017_holidaysection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='holidaysection',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='outing',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
    ]
