# Generated by Django 3.1.5 on 2021-05-22 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holiday', '0018_auto_20210117_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='description')),
                ('theme', models.CharField(max_length=255, verbose_name='theme')),
                ('bricolage', models.CharField(max_length=255, verbose_name='bricolage')),
                ('food', models.CharField(max_length=255, verbose_name='food')),
                ('game', models.CharField(max_length=255, verbose_name='game')),
                ('other', models.CharField(max_length=255, verbose_name='other')),
                ('animateur', models.ManyToManyField(related_name='holiday_weeks', to=settings.AUTH_USER_MODEL, verbose_name='animateur')),
                ('section_holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='holiday.holidaysection', verbose_name='section_holiday')),
            ],
            options={
                'verbose_name': 'section_program',
                'verbose_name_plural': 'section_programs',
            },
        ),
    ]
