# Generated by Django 3.1.5 on 2021-05-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday", "0023_auto_20210527_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="notes"),
        ),
    ]
