# Generated by Django 3.1.5 on 2021-06-02 08:17

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0025_auto_20210601_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='blacklisted_dates',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DateField(), default=list, size=None, verbose_name='blacklisted_dates'),
        ),
    ]
