# Generated by Django 3.1.5 on 2022-03-02 16:14

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0026_holiday_blacklisted_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='blacklisted_dates',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, null=True, size=None, verbose_name='blacklisted_dates'),
        ),
        migrations.AlterField(
            model_name='holidaysection',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_sections', to='holiday.holiday', verbose_name='holiday'),
        ),
    ]
