# Generated by Django 3.1.5 on 2022-03-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0027_auto_20220302_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='book_by_day',
            field=models.BooleanField(default=False, verbose_name='book_by_day'),
        ),
    ]
