# Generated by Django 3.1.5 on 2022-05-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0029_auto_20220525_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='outing',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
